# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:chx200205173214@tcp(120.25.255.207:3306)/go_gateway?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100